SELECT COUNT(*) FROM FTL_SEARCH('Maria Dorota', 0, 0);

SELECT P.* FROM FTL_SEARCH_DATA('Maria Dorota', 4, 0) FT, PEX P
WHERE FT.TABLE='PEX' AND P.ID=FT.KEYS[0]; 

SELECT P.* FROM FTL_SEARCH_DATA('Maria Dorota', 4, 4) FT, PEX P
WHERE FT.TABLE='PEX' AND P.ID=FT.KEYS[0]; 

SELECT P.* FROM FTL_SEARCH_DATA('Maria Dorota', 4, 8) FT, PEX P
WHERE FT.TABLE='PEX' AND P.ID=FT.KEYS[0]; 


SELECT COUNT(*) FROM PEX;

SELECT * FROM PEX 
ORDER BY PEX_DATE_MODIFIED DESC
LIMIT 4 OFFSET 0;

SELECT * FROM PEX 
ORDER BY PEX_DATE_MODIFIED DESC
LIMIT 4 OFFSET 4;

SELECT * FROM PEX 
ORDER BY PEX_DATE_MODIFIED DESC
LIMIT 4 OFFSET 8;
