
DROP TABLE IF EXISTS PEX_TEMP;

CREATE TABLE PEX_TEMP(
	ID IDENTITY PRIMARY KEY, 
	PEX_ID INT NOT NULL UNIQUE, 
	PEX_CASE_REF_NO NVARCHAR(255), 
	PEX_CAN_PUBLISH_CREDITOR_DATA BOOLEAN, 
	PEX_ENTITLEMENT_TEXT NVARCHAR(255), 
	PEX_ENTITLEMENT_DOCUMENT_REF_NO NVARCHAR(255), 
	PEX_ICUR_ID INT, 
	PEX_AMOUNT_TOTAL DECIMAL(20, 2), 
	PEX_AMOUNT_OPEN DECIMAL(20, 2), 
	PEX_DATE_DUE DATE, 
	PEX_DATE_MODIFIED DATETIME,

	DEBTOR_FIRST_NAME NVARCHAR(255), 
	DEBTOR_NAME NVARCHAR(255), 
	DEBTOR_NIP NVARCHAR(255), 
	DEBTOR_PESEL NVARCHAR(255), 
	DEBTOR_REGON NVARCHAR(255), 
	DEBTOR_STREET NVARCHAR(255), 
	DEBTOR_HOUSE_NUMBER NVARCHAR(255), 
	DEBTOR_FLAT_NUMBER NVARCHAR(255), 
	DEBTOR_ZIP NVARCHAR(255), 
	DEBTOR_IC_ID INT,

	CREDITOR_FIRST_NAME NVARCHAR(255), 
	CREDITOR_NAME NVARCHAR(255), 
	CREDITOR_NIP NVARCHAR(255), 
	CREDITOR_PESEL NVARCHAR(255), 
	CREDITOR_REGON NVARCHAR(255), 
	CREDITOR_STREET NVARCHAR(255), 
	CREDITOR_HOUSE_NUMBER NVARCHAR(255), 
	CREDITOR_FLAT_NUMBER NVARCHAR(255), 
	CREDITOR_ZIP NVARCHAR(255), 
	CREDITOR_IC_ID INT
);