CREATE TABLE data (key VARCHAR(255) PRIMARY KEY, value VARCHAR(1023) );

CREATE ALIAS IF NOT EXISTS FTL_INIT FOR "org.h2.fulltext.FullTextLucene.init";
CALL FTL_INIT();


CREATE TABLE TEST(ID INT PRIMARY KEY, NAME VARCHAR);
CALL FTL_CREATE_INDEX('PUBLIC', 'TEST', NULL);

INSERT INTO TEST VALUES(1, 'Hello World');
INSERT INTO TEST VALUES(2, 'Hello World1');
INSERT INTO TEST VALUES(3, 'Dupa');


CREATE TABLE TEST_TEMP(ID INT PRIMARY KEY, NAME VARCHAR);
--CALL FTL_CREATE_INDEX('PUBLIC', 'TEST_TEMP', NULL);

INSERT INTO TEST_TEMP VALUES(1, 'Hello World');
INSERT INTO TEST_TEMP VALUES(2, 'Hello World1');
INSERT INTO TEST_TEMP VALUES(3, 'Dupa');
INSERT INTO TEST_TEMP VALUES(4, 'Hello World1');

--DROP TABLE TEST;
--ALTER TABLE TEST_TEMP RENAME TO TEST;
--CALL FTL_REINDEX();

--FTL_CREATE_INDEX(schemaNameString, tableNameString, columnListString)
--FTL_SEARCH(queryString, limitInt, offsetInt): result set
--FTL_REINDEX()
--FTL_DROP_ALL()
--